version: "3"

# Define services
services:
  tweet-postgres-db:
    container_name: "tweet-postgres-db"
    image: postgres:14-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - network-api
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
  tweet-api:
    container_name: "tweet-api"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:8080
    depends_on:
      - tweet-postgres-db
    stdin_open: true
    tty: true
    networks:
      - network-api
    env_file:
      - .env

# Define volumes
volumes:
  database_postgres:

# Define networks
networks:
  network-api:
    driver: bridge
