// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecases/user/followed.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecases/user/followed.go -destination=internal/usecases/user/mocks/followed.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/tapiaw38/tweet-app/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockFollowedUsecase is a mock of FollowedUsecase interface.
type MockFollowedUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockFollowedUsecaseMockRecorder
}

// MockFollowedUsecaseMockRecorder is the mock recorder for MockFollowedUsecase.
type MockFollowedUsecaseMockRecorder struct {
	mock *MockFollowedUsecase
}

// NewMockFollowedUsecase creates a new mock instance.
func NewMockFollowedUsecase(ctrl *gomock.Controller) *MockFollowedUsecase {
	mock := &MockFollowedUsecase{ctrl: ctrl}
	mock.recorder = &MockFollowedUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFollowedUsecase) EXPECT() *MockFollowedUsecaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockFollowedUsecase) Execute(arg0 context.Context, arg1 domain.Follow) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockFollowedUsecaseMockRecorder) Execute(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockFollowedUsecase)(nil).Execute), arg0, arg1)
}
