// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/datasources/repositories/user/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/adapters/datasources/repositories/user/repository.go -destination=internal/adapters/datasources/repositories/user/mocks/repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
